import { FormularyHeader } from './FormularyHeader';
export class FormularyExclusions {
	formularyExclusionsIdPk?: number;
	formularyHeaderIdFk?: number;
	beginDate?: string;
	endDate?: string;
	currentFlag?: string;
	formularyId?: string;
	ndc?: string;
	included?: string;
	drugBrandName?: string;
	skeyHicl?: string;
	drugLabelName?: string;
	genericName?: string;
	stcDescription?: string;
	routeDescription?: string;
	dosageFormDescription?: string;
	strengthDescription?: string;
	drugIdType?: string;
	gpi2Code?: string;
	gpiCode?: string;
	brandGenericCode?: string;
	drugMultiSrcCode?: string;
	brandNameTypeCode?: string;
	maintDrugInd?: string;
	meddStatusCode?: string;
	spcltDrugInd?: string;
	rteAdminCode?: string;
	otcDrugInd?: string;
	frmlyNdcEffDate?: string;
	frmlyNdcExprnDate?: string;
	srcFrmlyInd?: string;
	srcFrmlyPdlCode?: string;
	frmlyPdlDescription?: string;
	monyCode?: string;
	monyDescription?: string;
	frmlyDrugTierNbrCode?: string;
	srcFrmlyDrugTierCode?: string;
	frmlyDrugTierDescription?: string;
	frmlyCmplcCode?: string;
	frmlyCmplcDescription?: string;
	frmlyListId?: string;
	frmlyListCode?: string;
	frmlyDrugSsTierRnkNbr?: string;
	frmlyDrugPrfrTierRelNbr?: string;
	frmlyDrugTierNbrMapId?: string;
	lastChangeDateTime?: string;
	lastChangeUser?: string;
	sourceIdFk?: number;
	formularyHeaderIdFkNavigation?: FormularyHeader;
	constructor(obj: any = {}) {
		this.formularyExclusionsIdPk = obj.formularyExclusionsIdPk;
		this.formularyHeaderIdFk = obj.formularyHeaderIdFk;
		this.beginDate = obj.beginDate;
		this.endDate = obj.endDate;
		this.currentFlag = obj.currentFlag;
		this.formularyId = obj.formularyId;
		this.ndc = obj.ndc;
		this.included = obj.included;
		this.drugBrandName = obj.drugBrandName;
		this.skeyHicl = obj.skeyHicl;
		this.drugLabelName = obj.drugLabelName;
		this.genericName = obj.genericName;
		this.stcDescription = obj.stcDescription;
		this.routeDescription = obj.routeDescription;
		this.dosageFormDescription = obj.dosageFormDescription;
		this.strengthDescription = obj.strengthDescription;
		this.drugIdType = obj.drugIdType;
		this.gpi2Code = obj.gpi2Code;
		this.gpiCode = obj.gpiCode;
		this.brandGenericCode = obj.brandGenericCode;
		this.drugMultiSrcCode = obj.drugMultiSrcCode;
		this.brandNameTypeCode = obj.brandNameTypeCode;
		this.maintDrugInd = obj.maintDrugInd;
		this.meddStatusCode = obj.meddStatusCode;
		this.spcltDrugInd = obj.spcltDrugInd;
		this.rteAdminCode = obj.rteAdminCode;
		this.otcDrugInd = obj.otcDrugInd;
		this.frmlyNdcEffDate = obj.frmlyNdcEffDate;
		this.frmlyNdcExprnDate = obj.frmlyNdcExprnDate;
		this.srcFrmlyInd = obj.srcFrmlyInd;
		this.srcFrmlyPdlCode = obj.srcFrmlyPdlCode;
		this.frmlyPdlDescription = obj.frmlyPdlDescription;
		this.monyCode = obj.monyCode;
		this.monyDescription = obj.monyDescription;
		this.frmlyDrugTierNbrCode = obj.frmlyDrugTierNbrCode;
		this.srcFrmlyDrugTierCode = obj.srcFrmlyDrugTierCode;
		this.frmlyDrugTierDescription = obj.frmlyDrugTierDescription;
		this.frmlyCmplcCode = obj.frmlyCmplcCode;
		this.frmlyCmplcDescription = obj.frmlyCmplcDescription;
		this.frmlyListId = obj.frmlyListId;
		this.frmlyListCode = obj.frmlyListCode;
		this.frmlyDrugSsTierRnkNbr = obj.frmlyDrugSsTierRnkNbr;
		this.frmlyDrugPrfrTierRelNbr = obj.frmlyDrugPrfrTierRelNbr;
		this.frmlyDrugTierNbrMapId = obj.frmlyDrugTierNbrMapId;
		this.lastChangeDateTime = obj.lastChangeDateTime;
		this.lastChangeUser = obj.lastChangeUser;
		this.sourceIdFk = obj.sourceIdFk;
		this.formularyHeaderIdFkNavigation = new FormularyHeader(obj.formularyHeaderIdFkNavigation);
	}
}
