import { UtPcaCalcLvlId } from './UtPcaCalcLvlId';
import { UtPcaCalcTypeId } from './UtPcaCalcTypeId';
import { UtPcaRbtProdId } from './UtPcaRbtProdId';
export class UtPcaCalcId {
	calcId?: number;
	rbtProdId?: number;
	calcNm?: number;
	calcGrpId1?: string;
	calcGrpId2?: string;
	calcGrpId3?: string;
	calcTypeId?: number;
	calcLvlId?: number;
	hpclntGrpId?: number;
	mktbsktId?: number;
	formId?: number;
	benefId?: number;
	critRateId?: number;
	otherCritId?: number;
	flatDiscType?: number;
	flatDiscValue?: number;
	calcEffecDt?: string;
	calcTermDt?: string;
	calcStampDt?: string;
	calcStampUsr?: string;
	calcNote?: string;
	calcCreateDate?: string;
	calcUpdateDate?: string;
	postCalcFlag?: number;
	calcRateCatId?: number;
	calcPriceProtectionMethodId?: number;
	calcPriceProtectionResetId?: number;
	lastChangeUser?: string;
	lastChangeDate?: string;
	calcLvl?: UtPcaCalcLvlId;
	calcType?: UtPcaCalcTypeId;
	rbtProd?: UtPcaRbtProdId;
	constructor(obj: any = {}) {
		this.calcId = obj.calcId;
		this.rbtProdId = obj.rbtProdId;
		this.calcNm = obj.calcNm;
		this.calcGrpId1 = obj.calcGrpId1;
		this.calcGrpId2 = obj.calcGrpId2;
		this.calcGrpId3 = obj.calcGrpId3;
		this.calcTypeId = obj.calcTypeId;
		this.calcLvlId = obj.calcLvlId;
		this.hpclntGrpId = obj.hpclntGrpId;
		this.mktbsktId = obj.mktbsktId;
		this.formId = obj.formId;
		this.benefId = obj.benefId;
		this.critRateId = obj.critRateId;
		this.otherCritId = obj.otherCritId;
		this.flatDiscType = obj.flatDiscType;
		this.flatDiscValue = obj.flatDiscValue;
		this.calcEffecDt = obj.calcEffecDt;
		this.calcTermDt = obj.calcTermDt;
		this.calcStampDt = obj.calcStampDt;
		this.calcStampUsr = obj.calcStampUsr;
		this.calcNote = obj.calcNote;
		this.calcCreateDate = obj.calcCreateDate;
		this.calcUpdateDate = obj.calcUpdateDate;
		this.postCalcFlag = obj.postCalcFlag;
		this.calcRateCatId = obj.calcRateCatId;
		this.calcPriceProtectionMethodId = obj.calcPriceProtectionMethodId;
		this.calcPriceProtectionResetId = obj.calcPriceProtectionResetId;
		this.lastChangeUser = obj.lastChangeUser;
		this.lastChangeDate = obj.lastChangeDate;
		this.calcLvl = new UtPcaCalcLvlId(obj.calcLvl);
		this.calcType = new UtPcaCalcTypeId(obj.calcType);
		this.rbtProd = new UtPcaRbtProdId(obj.rbtProd);
	}
}
