import { UtPcaFormId } from './UtPcaFormId';
export class UtPcaFormDefnId {
	formDefnId?: number;
	formId?: number;
	formDefnTierValBdl?: number;
	formDefnTierVal?: number;
	formDefnTierValBdl1?: number;
	formDefnTierVal1?: number;
	formDefnTierValBdl2?: number;
	formDefnTierVal2?: number;
	formDefnTierValBdl3?: number;
	formDefnTierVal3?: number;
	formDefnTierValBdl4?: number;
	formDefnTierVal4?: number;
	formDefnTierValBdl5?: number;
	formDefnTierVal5?: number;
	formDefnTierValBdl6?: number;
	formDefnTierVal6?: number;
	formDefnTierValBdl7?: number;
	formDefnTierVal7?: number;
	formDefnTierValBdl8?: number;
	formDefnTierVal8?: number;
	formDefnRateVal?: number;
	critRateId?: number;
	termVio?: boolean;
	formDefnCreateDate?: string;
	formDefnUpdateDate?: string;
	formDefnTierValDropX1?: number;
	formDefnTierValDropY1?: number;
	formDefnTierValDropX2?: number;
	formDefnTierValDropY2?: number;
	formDefnTierValDropX3?: number;
	formDefnTierValDropY3?: number;
	formDefnTierValDropX4?: number;
	formDefnTierValDropY4?: number;
	formDefnTierValDropX5?: number;
	formDefnTierValDropY5?: number;
	formDefnTierValDropX6?: number;
	formDefnTierValDropY6?: number;
	formDefnTierValDropX7?: number;
	formDefnTierValDropY7?: number;
	formDefnTierValDropX8?: number;
	formDefnTierValDropY8?: number;
	formDefnLabel?: string;
	formPriceProtectionResetId?: number;
	formPriceProtectionMethodId?: number;
	lastChangeUser?: string;
	lastChangeDate?: string;
	form?: UtPcaFormId;
	constructor(obj: any = {}) {
		this.formDefnId = obj.formDefnId;
		this.formId = obj.formId;
		this.formDefnTierValBdl = obj.formDefnTierValBdl;
		this.formDefnTierVal = obj.formDefnTierVal;
		this.formDefnTierValBdl1 = obj.formDefnTierValBdl1;
		this.formDefnTierVal1 = obj.formDefnTierVal1;
		this.formDefnTierValBdl2 = obj.formDefnTierValBdl2;
		this.formDefnTierVal2 = obj.formDefnTierVal2;
		this.formDefnTierValBdl3 = obj.formDefnTierValBdl3;
		this.formDefnTierVal3 = obj.formDefnTierVal3;
		this.formDefnTierValBdl4 = obj.formDefnTierValBdl4;
		this.formDefnTierVal4 = obj.formDefnTierVal4;
		this.formDefnTierValBdl5 = obj.formDefnTierValBdl5;
		this.formDefnTierVal5 = obj.formDefnTierVal5;
		this.formDefnTierValBdl6 = obj.formDefnTierValBdl6;
		this.formDefnTierVal6 = obj.formDefnTierVal6;
		this.formDefnTierValBdl7 = obj.formDefnTierValBdl7;
		this.formDefnTierVal7 = obj.formDefnTierVal7;
		this.formDefnTierValBdl8 = obj.formDefnTierValBdl8;
		this.formDefnTierVal8 = obj.formDefnTierVal8;
		this.formDefnRateVal = obj.formDefnRateVal;
		this.critRateId = obj.critRateId;
		this.termVio = obj.termVio;
		this.formDefnCreateDate = obj.formDefnCreateDate;
		this.formDefnUpdateDate = obj.formDefnUpdateDate;
		this.formDefnTierValDropX1 = obj.formDefnTierValDropX1;
		this.formDefnTierValDropY1 = obj.formDefnTierValDropY1;
		this.formDefnTierValDropX2 = obj.formDefnTierValDropX2;
		this.formDefnTierValDropY2 = obj.formDefnTierValDropY2;
		this.formDefnTierValDropX3 = obj.formDefnTierValDropX3;
		this.formDefnTierValDropY3 = obj.formDefnTierValDropY3;
		this.formDefnTierValDropX4 = obj.formDefnTierValDropX4;
		this.formDefnTierValDropY4 = obj.formDefnTierValDropY4;
		this.formDefnTierValDropX5 = obj.formDefnTierValDropX5;
		this.formDefnTierValDropY5 = obj.formDefnTierValDropY5;
		this.formDefnTierValDropX6 = obj.formDefnTierValDropX6;
		this.formDefnTierValDropY6 = obj.formDefnTierValDropY6;
		this.formDefnTierValDropX7 = obj.formDefnTierValDropX7;
		this.formDefnTierValDropY7 = obj.formDefnTierValDropY7;
		this.formDefnTierValDropX8 = obj.formDefnTierValDropX8;
		this.formDefnTierValDropY8 = obj.formDefnTierValDropY8;
		this.formDefnLabel = obj.formDefnLabel;
		this.formPriceProtectionResetId = obj.formPriceProtectionResetId;
		this.formPriceProtectionMethodId = obj.formPriceProtectionMethodId;
		this.lastChangeUser = obj.lastChangeUser;
		this.lastChangeDate = obj.lastChangeDate;
		this.form = new UtPcaFormId(obj.form);
	}
}
